### ISSUE TITLE
local-weaver dependency

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/rad#5]
I'm having trouble building the rad project (in order to build prophet-utils), since it has a dependency on local-weaver which is available on seer.ecs.baylor.edu, which is currently down. Is it possible to remove this dependency?

**Comment by diptadas** [comment]
- https://github.com/cloudhubs/rad/commit/3be9322da20ef4e2efd6203e1677282cf842a71c
- https://github.com/cloudhubs/rad/commit/7cf02f8b1cacb7323b5432016dd73960fb8231f2
